name: grisette
version: 0.1.0.0
synopsis: Monadic symbolic compilation
description: Monadic library for a symbolic host language in haskell
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette-core
- grisette-symir
- grisette-lib
- grisette-backend-sbv
- sbv
- generic-deriving

# default-extensions:
# - BangPatterns
# - ConstraintKinds
# - DataKinds
# - DefaultSignatures
# - DeriveGeneric
# - DeriveLift
# - FlexibleContexts
# - FlexibleInstances
# - FunctionalDependencies
# - GADTs
# - KindSignatures
# - LambdaCase
# - MultiParamTypeClasses
# - RankNTypes
# - ScopedTypeVariables
# - TypeApplications
# - TypeFamilies
# - TypeOperators
# - DeriveAnyClass

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src
