name: grisette-symir
version: 0.1.0.0
synopsis: Symbolic IR
description: Default symbolic IR implementation for grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette-core
- intern
- hashable
- mtl
- unordered-containers
- monad-memo
- bv-sized
- constraints
- template-haskell
- deepseq
- MemoTrie
- array
- typerep-map
- vector
- parameterized-utils
- th-compat

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - grisette-symir
      - hspec-junit-formatter
