name: grisette-symir
version: 0.1.0.0
synopsis: Symbolic IR
description: Default symbolic IR implementation for grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- intern >= 0.9.2
- hashable >= 1.3
- mtl >= 2.2.2
- unordered-containers >= 0.2.11
- bv-sized >= 1.0.3 && <= 1.0.4
- template-haskell >= 2.16
- deepseq >= 1.4.4
- array >= 0.5.4.0
- typerep-map >= 0.3.3
- vector >= 0.12.1.2
- parameterized-utils >= 2.1.4
- th-compat >= 0.1.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - grisette-symir
      - hspec-junit-formatter
