name: grisette-doctest
version: 0.1.0.0
synopsis: Doctest for Grisette
description: Doctest for Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- intern >= 0.9.2
- hashable >= 1.3
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- generic-deriving >= 1.14.1
- constraints >= 0.11
- bytestring >= 0.10.12
- monad-coroutine >= 0.9.0.4
- unordered-containers >= 0.2.11
- template-haskell >= 2.16
- deepseq >= 1.4.4
- MemoTrie >= 0.6.10
- vector-sized >= 1.4.1
- vector >= 0.12.1.2
- parameterized-utils >= 2.1.4
- hashtables >= 1.2.3.4
- Unique >= 0.4.7
- loch-th >= 0.2.2
- typerep-map >= 0.3.3
- bv-sized >= 1.0.3
- array >= 0.5.4.0
- sbv >= 8.11
- th-compat >= 0.1.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - grisette-core
      - grisette-symir
      - grisette-lib
      - grisette-backend-sbv
      - grisette
      - grisette-tutorial
      - doctest >= 0.19.0
      - Glob
