version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dep-{{ checksum "stack.yaml" }}-{{ checksum "core/package.yaml" }}-{{ checksum "symprim/package.yaml" }}-{{ checksum "smt/package.yaml" }}-{{ checksum "lib/package.yaml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "scratch/package.yaml" }}-{{ checksum "examples/package.yaml" }}-
            - dep-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests (for core)
          command: stack --no-terminal test grisette-core --flag grisette-core:-fast
      - save_cache:
          name: Cache Dependencies
          key: dep-{{ checksum "stack.yaml" }}-{{ checksum "core/package.yaml" }}-{{ checksum "symprim/package.yaml" }}-{{ checksum "smt/package.yaml" }}-{{ checksum "lib/package.yaml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "scratch/package.yaml" }}-{{ checksum "examples/package.yaml" }}-
          paths:
            - "/root/.stack"
            - ".stack-work"
            - "core/.stack-work"
            - "symprim/.stack-work"
            - "smt/.stack-work"
            - "lib/.stack-work"
            - "grisette/.stack-work"
            - "examples/.stack-work"
            - "scratch/.stack-work"
