name: grisette-monad-coroutine
version: 0.1.0.0
synopsis: Support for monad-coroutine package with Grisette
description: Orphan instances and wrappers for monad-coroutine package with Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- monad-coroutine >= 0.9.0.4

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - grisette-core
      - grisette-monad-coroutine
      - hspec-junit-formatter

