version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dep-{{ checksum "stack.yaml" }}-{{ checksum .circleci/config.yml }}-{{ checksum "core/grisette-core.cabal" }}-{{ checksum "symprim/grisette-symprim.cabal" }}-{{ checksum "smt/grisette-smt.cabal" }}-{{ checksum "lib/grisette-lib.cabal" }}-{{ checksum "grisette/grisette.cabal" }}-{{ checksum "scratch/grisette-scratch.cabal" }}-{{ checksum "examples/grisette-examples.cabal" }}-
            - dep-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: apt update && apt install -y pkg-config git curl libpcre2-dev libpcre3-dev && stack --no-terminal setup
      - run:
          name: Run tests (for core)
          command: stack --no-terminal test --flag grisette-core:-fast --flag grisette-examples:-fast --flag grisette-lib:-fast --flag grisette:-fast --flag grisette-scratch:-fast --flag grisette-smt:-fast --flag grisette-symprim:-fast --coverage
      - save_cache:
          name: Cache Dependencies
          key: dep-{{ checksum "stack.yaml" }}-{{ checksum .circleci/config.yml }}-{{ checksum "core/grisette-core.cabal" }}-{{ checksum "symprim/grisette-symprim.cabal" }}-{{ checksum "smt/grisette-smt.cabal" }}-{{ checksum "lib/grisette-lib.cabal" }}-{{ checksum "grisette/grisette.cabal" }}-{{ checksum "scratch/grisette-scratch.cabal" }}-{{ checksum "examples/grisette-examples.cabal" }}-
          paths:
            - "/root/.stack"
            - ".stack-work"
            - "core/.stack-work"
            - "symprim/.stack-work"
            - "smt/.stack-work"
            - "lib/.stack-work"
            - "grisette/.stack-work"
            - "examples/.stack-work"
            - "scratch/.stack-work"
      - run:
          name: Upload shc
          command: wget https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.6.1/shc-linux-x64-8.10.4.tar.bz2 && tar -xjf shc-linux-x64-8.10.4.tar.bz2 && ./shc --repo-token=$COVERALLS_REPO_TOKEN grisette-core spec
