version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dep-{{ checksum "stack.yaml" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "grisette-core/package.yaml" }}-{{ checksum "grisette-symir/package.yaml" }}-{{ checksum "grisette-backend-sbv/package.yaml" }}-{{ checksum "grisette-lib/package.yaml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "grisette-scratch/package.yaml" }}-{{ checksum "grisette-examples/package.yaml" }}-{{ checksum "grisette-benchmarks/package.yaml" }}-{{ checksum "grisette-backend-direct/package.yaml" }}-{{ checksum "grisette-doctest/package.yaml" }}
            - dep-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: |
            rm -rf /etc/apt/sources.list.d/*
            apt update
            apt install -y pkg-config git curl libpcre2-dev libpcre3-dev
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip
            unzip z3-4.8.10-x64-ubuntu-18.04.zip
            cp z3-4.8.10-x64-ubuntu-18.04/bin/z3 /usr/bin
            stack --no-terminal setup
      - run:
          name: Run tests
          command: |
            stack --no-terminal clean
            stack --no-terminal test --flag grisette-core:-fast --flag grisette-examples:-fast --flag grisette-lib:-fast --flag grisette:-fast --flag grisette-scratch:-fast --flag grisette-backend-sbv:-fast --flag grisette-symir:-fast --flag grisette-benchmarks:-fast --flag grisette-tutorial:-fast --flag grisette-backend-direct:-fast --coverage
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Upload shc
          command: wget https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.6.1/shc-linux-x64-8.10.4.tar.bz2 && tar -xjf shc-linux-x64-8.10.4.tar.bz2 && ./shc --repo-token=$COVERALLS_REPO_TOKEN combined all
      - run:
          name: Build doc
          command: |
            stack --no-terminal haddock --flag grisette-core:-fast --flag grisette-examples:-fast --flag grisette-lib:-fast --flag grisette:-fast --flag grisette-scratch:-fast --flag grisette-backend-sbv:-fast --flag grisette-symir:-fast --flag grisette-benchmarks:-fast --flag grisette-tutorial:-fast --flag grisette-backend-direct:-fast
            rm -rf /tmp/grisette-doc
            mkdir -p /tmp/grisette-doc
            cp -r $(stack path --local-doc-root)/grisette-* /tmp/grisette-doc
      - store_artifacts:
          path: "/tmp/grisette-doc"
      - run:
          name: Clean up
          command: stack --no-terminal clean
      - save_cache:
          name: Cache Dependencies
          key: dep-{{ checksum "stack.yaml" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "grisette-core/package.yaml" }}-{{ checksum "grisette-symir/package.yaml" }}-{{ checksum "grisette-backend-sbv/package.yaml" }}-{{ checksum "grisette-lib/package.yaml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "grisette-scratch/package.yaml" }}-{{ checksum "grisette-examples/package.yaml" }}-{{ checksum "grisette-benchmarks/package.yaml" }}-{{ checksum "grisette-backend-direct/package.yaml" }}-{{ checksum "grisette-doctest/package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
            - "grisette-core/.stack-work"
            - "grisette-symir/.stack-work"
            - "grisette-backend-sbv/.stack-work"
            - "grisette-backend-direct/.stack-work"
            - "grisette-lib/.stack-work"
            - "grisette/.stack-work"
            - "grisette-examples/.stack-work"
            - "grisette-scratch/.stack-work"
            - "grisette-benchmarks/.stack-work"
            - "grisette-tutorial/.stack-work"
            - "grisette-doctest/.stack-work"
