version: 2.1
jobs:
  build:
    parameters:
      yamlver:
        type: string
    docker:
      - image: fpco/stack-build:lts
    resource_class: large
    steps:
      - checkout
      - run:
          name: Link stack.yaml
          command: |
            rm -f stack.yaml stack.yaml.lock
            ln -s stack-<< parameters.yamlver >>.yaml stack.yaml
            cp stack-<< parameters.yamlver >>.yaml.lock stack.yaml.lock
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - dep-{{ checksum "stack.yaml" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "grisette-backend-direct/package.yaml" }}-{{ checksum "grisette-backend-sbv/package.yaml" }}-{{ checksum "grisette-benchmarks/package.yaml" }}-{{ checksum "grisette-core/package.yaml" }}-{{ checksum "grisette-doctest/package.yaml" }}-{{ checksum "grisette-examples/package.yaml" }}-{{ checksum "grisette-lib/package.yaml" }}-{{ checksum "grisette-monad-coroutine/package.yaml" }}-{{ checksum "grisette-scratch/package.yaml" }}-{{ checksum "grisette-symir/package.yaml" }}-{{ checksum "grisette-tutorial/package.yaml" }}-{{ checksum "grisette-vector-sized/package.yaml" }}-{{ checksum "grisette-fused-effects/package.yaml" }}-{{ checksum "grisette-cbmcencoding/package.yaml" }}-{{ checksum "grisette-unordered/package.yaml" }}
            - dep-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: |
            rm -rf /etc/apt/sources.list.d/*
            apt update
            apt install -y pkg-config git curl libpcre2-dev libpcre3-dev unzip
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip
            unzip z3-4.8.10-x64-ubuntu-18.04.zip
            cp z3-4.8.10-x64-ubuntu-18.04/bin/z3 /usr/bin
            stack --no-terminal setup
      - run:
          name: Run tests
          command: |
            stack --stack-yaml stack.yaml --no-terminal clean
            stack --stack-yaml stack.yaml --no-terminal test --coverage
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Upload shc
          command: wget https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.6.1/shc-linux-x64-8.10.4.tar.bz2 && tar -xjf shc-linux-x64-8.10.4.tar.bz2 && ./shc --repo-token=$COVERALLS_REPO_TOKEN combined all
      - run:
          name: Build doc
          command: |
            stack --stack-yaml stack.yaml --no-terminal haddock
            rm -rf /tmp/grisette-doc
            mkdir -p /tmp/grisette-doc
            cp -r $(stack path --stack-yaml stack.yaml --local-doc-root)/grisette-* /tmp/grisette-doc
      - store_artifacts:
          path: "/tmp/grisette-doc"
      - run:
          name: Clean up
          command: stack --stack-yaml stack.yaml --no-terminal clean
      - save_cache:
          name: Cache Dependencies
          key: dep-{{ checksum "stack.yaml" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "grisette/package.yaml" }}-{{ checksum "grisette-backend-direct/package.yaml" }}-{{ checksum "grisette-backend-sbv/package.yaml" }}-{{ checksum "grisette-benchmarks/package.yaml" }}-{{ checksum "grisette-core/package.yaml" }}-{{ checksum "grisette-doctest/package.yaml" }}-{{ checksum "grisette-examples/package.yaml" }}-{{ checksum "grisette-lib/package.yaml" }}-{{ checksum "grisette-monad-coroutine/package.yaml" }}-{{ checksum "grisette-scratch/package.yaml" }}-{{ checksum "grisette-symir/package.yaml" }}-{{ checksum "grisette-tutorial/package.yaml" }}-{{ checksum "grisette-vector-sized/package.yaml" }}-{{ checksum "grisette-fused-effects/package.yaml" }}-{{ checksum "grisette-cbmcencoding/package.yaml" }}-{{ checksum "grisette-unordered/package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
            - "grisette/.stack-work"
            - "grisette-backend-direct/.stack-work"
            - "grisette-backend-sbv/.stack-work"
            - "grisette-benchmarks/.stack-work"
            - "grisette-core/.stack-work"
            - "grisette-doctest/.stack-work"
            - "grisette-examples/.stack-work"
            - "grisette-lib/.stack-work"
            - "grisette-monad-coroutine/.stack-work"
            - "grisette-scratch/.stack-work"
            - "grisette-symir/.stack-work"
            - "grisette-tutorial/.stack-work"
            - "grisette-vector-sized/.stack-work"
            - "grisette-fused-effects/.stack-work"
            - "grisette-unordered/.stack-work"
            - "grisette-cbmcencoding/.stack-work"

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              yamlver: ["lts-18.28-lowerbound", "lts-18.28", "lts-19.6"]
