name: grisette-tutorial
version: 0.1.0.0
synopsis: Documented tutorials by examples for Grisette
description: Grisette tutorials
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette
- mtl
- transformers
- monad-coroutine
- bytestring
- regex-base
- regex-pcre
- hashable
- MemoTrie
- monad-memo
- loch-th
- template-haskell
- th-lift-instances
- utf8-string
- unordered-containers
- megaparsec
- parser-combinators
- timeit
- clock
- formatting
- deepseq
- Unique
- bv-sized
- vector-sized
- parameterized-utils
- either
- hashtables
- generic-deriving

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src
