name: grisette-tutorial
version: 0.1.0.0
synopsis: Documented tutorials by examples for Grisette
description: Grisette tutorials
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- monad-coroutine >= 0.9.0.4
- bytestring >= 0.10.12
- regex-base >= 0.94
- regex-pcre-builtin >= 0.95.1.1.8.44
- hashable >= 1.3
- loch-th >= 0.2.2
- template-haskell >= 2.16
- th-lift-instances >= 0.1.16
- utf8-string >= 1.0.1.1
- unordered-containers >= 0.2.11
- megaparsec >= 8
- parser-combinators >= 1
- timeit >= 1.0
- clock >= 0.7.1
- formatting >= 6.3.1
- deepseq >= 1.4.4
- Unique >= 0.4.7
- vector-sized >= 1.4.1
- either >= 5
- hashtables >= 1.2.3.4
- generic-deriving >= 1.14.1
- sbv >= 8.11

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src
