name: grisette-vector-sized
version: 0.1.0.0
synopsis: Support for vector-sized package with Grisette
description: Orphan instances and wrappers for vector-sized package with Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- vector >= 0.12.1.2
- vector-sized >= 1.4.1
- parameterized-utils >= 2.1.4

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - grisette-core
      - grisette-vector-sized
      - unordered-containers >= 0.2.11
      - hspec-junit-formatter


