{-# LANGUAGE PatternSynonyms #-}

module Grisette.Internal.SymPrim.Term
  ( Union,
    UnaryOp (..),
    BinaryOp (..),
    TernaryOp (..),
    Term (..),
    introSupportedPrimConstraint,
    SomeTerm (..),
    SupportedPrim (..),
    Symbol (..),
    castTerm,
    identity,
    identityWithTypeRep,
    pformat,
    constructUnary,
    constructBinary,
    constructTernary,
    concTerm,
    symbTerm,
    ssymbTerm,
    isymbTerm,
    extractSymbolicsTerm,
    TermSymbol (..),
    trueTerm,
    falseTerm,
    pattern BoolConcTerm,
    pattern TrueTerm,
    pattern FalseTerm,
    pattern BoolTerm,
    Not (..),
    notb,
    pattern NotTerm,
    Eqv (..),
    eqterm,
    neterm,
    pattern EqvTerm,
    Or (..),
    orb,
    pattern OrTerm,
    And (..),
    andb,
    pattern AndTerm,
    ITE (..),
    iteterm,
    pattern ITETerm,
    implyb,
    xorb,
    unaryUnfoldOnce,
    binaryUnfoldOnce,
    pattern SignedBVConcTerm,
    pattern SignedBVTerm,
    pattern UnsignedBVConcTerm,
    pattern UnsignedBVTerm,
    pattern UnaryTermPatt,
    pattern BinaryTermPatt,
    pattern TernaryTermPatt,
    PartialFunc,
    PartialRuleUnary,
    TotalRuleUnary,
    PartialRuleBinary,
    TotalRuleBinary,
    totalize,
    totalize2,
    UnaryPartialStrategy (..),
    unaryPartial,
    BinaryCommPartialStrategy (..),
    BinaryPartialStrategy (..),
    binaryPartial,
    integerConcTermView,
    pattern IntegerConcTerm,
    pattern IntegerTerm,
    DivI (..),
    divi,
    pattern DivITerm,
    ModI (..),
    modi,
    pattern ModITerm,
    pattern NumConcTerm,
    pattern NumOrdConcTerm,
    AddNum (..),
    addNum,
    pattern AddNumTerm,
    minusNum,
    UMinusNum (..),
    uminusNum,
    pattern UMinusNumTerm,
    AbsNum (..),
    absNum,
    pattern AbsNumTerm,
    SignumNum (..),
    signumNum,
    pattern SignumNumTerm,
    TimesNum (..),
    timesNum,
    pattern TimesNumTerm,
    LTNum (..),
    ltNum,
    pattern LTNumTerm,
    LENum (..),
    leNum,
    pattern LENumTerm,
    gtNum,
    geNum,
    pattern TabularFuncConcTerm,
    pattern TabularFuncTerm,
    ApplyF (..),
    applyf,
    pattern ApplyFTerm,
  )
where

import Grisette.Data.Prim.BV
import Grisette.Data.Prim.Bool
import Grisette.Data.Prim.Helpers
import Grisette.Data.Prim.Integer
import Grisette.Data.Prim.InternedTerm
import Grisette.Data.Prim.Num
import Grisette.Data.Prim.TabularFunc
import Grisette.Data.Union
