name: grisette-core
version: 0.1.0.0
synopsis: Monadic symbolic compilation
description: Monadic library for a symbolic host language in haskell
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- intern
- hashable
- mtl
- transformers
- generic-deriving
- monad-coroutine
- constraints
- bytestring
- unordered-containers
- monad-memo
- template-haskell

library:
  source-dirs: src
  ghc-options: -Wall -ferror-spans -O2

