name: grisette-benchmarks
version: 0.1.0.0
synopsis: Benchmark set for Grisette
description: Example symbolic DSLs for benchmarking purpose
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette
- mtl
- transformers
- monad-coroutine
- bytestring
- regex-base
- regex-pcre
- hashable
- MemoTrie
- monad-memo
- loch-th
- template-haskell
- th-lift-instances
- utf8-string
- unordered-containers
- megaparsec
- parser-combinators
- timeit
- clock
- formatting
- deepseq
- Unique
- bv-sized
- vector-sized
- parameterized-utils
- either
- hashtables
- generic-deriving
- text

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs:
    - utils
    - bonsai-lib

executables:
  fluidics:
    source-dirs: fluidics
    main: Main.hs
    dependencies: grisette-benchmarks
  ferrite:
    source-dirs: ferrite
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-nanoscala:
    source-dirs: bonsai-nanoscala
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-letpoly:
    source-dirs: bonsai-letpoly
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-stlc:
    source-dirs: bonsai-stlc
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-nanoscala-nomemo:
    source-dirs: bonsai-nanoscala-nomemo
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-letpoly-nomemo:
    source-dirs: bonsai-letpoly-nomemo
    main: Main.hs
    dependencies: grisette-benchmarks
  bonsai-stlc-nomemo:
    source-dirs: bonsai-stlc-nomemo
    main: Main.hs
    dependencies: grisette-benchmarks
  cosette:
    source-dirs: cosette
    main: Benchmark/Main.hs
    dependencies: grisette-benchmarks
  cosette-optimized-merge:
    source-dirs: cosette-optimized-merge
    main: Benchmark/Main.hs
    dependencies: grisette-benchmarks
  ifcl:
    source-dirs: ifcl
    main: Main.hs
    dependencies: grisette-benchmarks
  regex:
    source-dirs: regex
    main: Main.hs
    dependencies: grisette-benchmarks
  regex-nomemo:
    source-dirs: regex-nomemo
    main: Main.hs
    dependencies: grisette-benchmarks