name: grisette-examples
version: 0.1.0.0
synopsis: Example code for Grisette
description: Example symbolic DSLs
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette
- mtl
- transformers
- monad-coroutine
- bytestring
- regex-base
- regex-pcre
- hashable
- MemoTrie
- monad-memo
- loch-th
- template-haskell
- th-lift-instances
- utf8-string
- unordered-containers
- megaparsec
- parser-combinators
- timeit
- clock
- formatting
- deepseq
- Unique
- bv-sized

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options: -Wall -ferror-spans -O2

library:
  source-dirs: utils

executables:
  expr-interpreter:
    source-dirs: expr-interpreter
    main: Main.hs
  regex:
    source-dirs: regex
    main: Main.hs
  order:
    source-dirs: order
    main: Main.hs
  location:
    source-dirs: location
    main: Main.hs
  genfunc:
    source-dirs: genfunc
    main: Main.hs
  fluidics:
    source-dirs: fluidics
    main: Main.hs
    dependencies: grisette-examples
  cosette:
    source-dirs: cosette
    main: Benchmark/Main.hs
  expr-sketch:
    source-dirs: expr-sketch
    main: Main.hs
  stmt-sketch:
    source-dirs: stmt-sketch
    main: Main.hs
  tutorial:
    source-dirs: tutorial
    main: Main.hs


