name: grisette-scratch
version: 0.1.0.0
synopsis: Example code for Grisette
description: Example symbolic DSLs
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- MemoTrie >= 0.6.10
- vector >= 0.12.1.2
- fused-effects >= 1.0.2.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

executables:
  list-funcs:
    source-dirs: list-funcs
    main: Main.hs
  interned-trie:
    source-dirs: interned-trie
    main: Main.hs
  cegis:
    source-dirs: cegis
    main: Main.hs
  angelic:
    source-dirs: angelic
    main: Main.hs
  effects:
    source-dirs: effects
    main: Main.hs
  
library:
  source-dirs: src
