name: grisette-symprim
version: 0.1.0.0
synopsis: Symbolic primitives
description: Default symbolic primitives implementation for grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette-core
- intern
- hashable
- mtl
- unordered-containers
- monad-memo
- bv-sized
- constraints
- template-haskell
- deepseq
- MemoTrie
- array
- typerep-map
- vector

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DeriveLift
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- DeriveAnyClass

library:
  source-dirs: src
  ghc-options: -Wall -ferror-spans -O2

