name: grisette-core
version: 0.1.0.0
synopsis: Monadic symbolic compilation
description: Monadic library for a symbolic host language in haskell
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- hashable >= 1.3
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- generic-deriving >= 1.14.1
- monad-coroutine >= 0.9.0.4
- constraints >= 0.11
- bytestring >= 0.10.12
- unordered-containers >= 0.2.11
- template-haskell >= 2.16
- deepseq >= 1.4.4
- MemoTrie >= 0.6.10
- vector-sized >= 1.4.1
- vector >= 0.12.1.2
- parameterized-utils >= 2.1.4
- hashtables >= 1.2.3.4
- loch-th >= 0.2.2
- th-compat >= 0.1.2

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    main: Main.hs
    dependencies:
      - grisette-core
      - hspec-junit-formatter
