name: grisette-examples
version: 0.1.0.0
synopsis: Example code for Grisette
description: Example symbolic DSLs
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette == 0.1.0.0
- grisette-megaparsec == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- bytestring >= 0.10.12
- loch-th >= 0.2.2
- template-haskell >= 2.16
- utf8-string >= 1.0.1.1
- megaparsec >= 8
- parser-combinators >= 1
- clock >= 0.7.1
- formatting >= 6.3.1
- generic-deriving >= 1.14.1
- unordered-containers >= 0.2.11
- QuickCheck >= 2.13.2
- timeit >= 1.0
- hashable >= 1.3
- text >= 1.2.4.1

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: utils

executables:
  expr-interpreter:
    source-dirs: expr-interpreter
    main: Main.hs
  order:
    source-dirs: order
    main: Main.hs
  location:
    source-dirs: location
    main: Main.hs
  genfunc:
    source-dirs: genfunc
    main: Main.hs
  expr-sketch:
    source-dirs: expr-sketch
    main: Main.hs
  stmt-sketch:
    source-dirs: stmt-sketch
    main: Main.hs
  tutorial:
    source-dirs: tutorial
    main: Main.hs
  dpsynth:
    source-dirs: dpsynth
    main: Main.hs
    dependencies: grisette-examples
  formula-optimization:
    source-dirs: formula-optimization
    main: Main.hs
    dependencies: grisette-examples



