name: grisette-lib
version: 0.1.0.0
synopsis: Extra Grisette library
description: Extra Grisette library, data structures and lifted functions
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- grisette-symir == 0.1.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- monad-coroutine >= 0.9.0.4
- MemoTrie >= 0.6.10

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs: src

