name: grisette-scratch
version: 0.1.0.0
synopsis: Example code for Grisette
description: Example symbolic DSLs
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu"
maintainer: siruilu@uw.edu
license: BSD3
github: lsrcz/grisette-haskell
copyright: "2021 Sirui Lu"

dependencies:
- base > 4.7 && < 5
- grisette
- mtl
- transformers
- monad-coroutine
- bytestring
- regex-base
- regex-pcre
- hashable
- MemoTrie
- monad-memo
- loch-th
- template-haskell
- utf8-string
- unordered-containers
- vector

flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

executables:
  list-funcs:
    source-dirs: list-funcs
    main: Main.hs
  interned-trie:
    source-dirs: interned-trie
    main: Main.hs
  cegis:
    source-dirs: cegis
    main: Main.hs
  

