name: grisette-unordered
version: 0.1.0.0
synopsis: Monadic symbolic compilation
description: Monadic library for a symbolic host language in haskell
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT

dependencies:
- base > 4.14 && < 5
- grisette-core == 0.1.0.0
- grisette-symir == 0.1.0.0
- grisette-backend-sbv == 0.1.0.0
- grisette-lib == 0.1.0.0
- grisette-monad-coroutine == 0.1.0.0
- grisette == 0.1.0.0
- hashable >= 1.3
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- generic-deriving >= 1.14.1
- bytestring >= 0.10.12
- unordered-containers >= 0.2.11
- containers >= 0.2.11
- template-haskell >= 2.16
- deepseq >= 1.4.4
- hashtables >= 1.2.3.4
- loch-th >= 0.2.2
- th-compat >= 0.1.2
- hspec == 2.*
- bv-sized >= 1.0.3
- Unique >= 0.4.7
- clock >= 0.7.1
- formatting >= 6.3.1
- text >= 1.2.4.1
- either >= 5
- regex-base >= 0.94
- regex-pcre-builtin >= 0.95.1.1.8.44
- monad-coroutine >= 0.9.0.4
- natural-transformation >= 0.3
- th-lift-instances >= 0.1.16
- megaparsec >= 8
- parser-combinators >= 1

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators


flags: {
  fast: {
    description: "Compile with O2 optimization",
    manual: False,
    default: True,
  }
}

when:
  - condition: flag(fast)
    then:
      ghc-options: -O2
    else:
      ghc-options: -O0

ghc-options: -Wall -ferror-spans

library:
  source-dirs:
    - utils
    - bonsai-lib
    - regex-common
    - coroutine-lib
    - src

executables:
  fluidics-unordered:
    source-dirs: fluidics-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  ferrite-unordered:
    source-dirs: ferrite-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  ifcl-unordered:
    source-dirs: ifcl-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-letpoly-unordered:
    source-dirs: bonsai-letpoly-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-letpoly-nomemo-unordered:
    source-dirs: bonsai-letpoly-nomemo-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-stlc-unordered:
    source-dirs: bonsai-stlc-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-stlc-nomemo-unordered:
    source-dirs: bonsai-stlc-nomemo-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-nanoscala-unordered:
    source-dirs: bonsai-nanoscala-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  bonsai-nanoscala-nomemo-unordered:
    source-dirs: bonsai-nanoscala-nomemo-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  regex-unordered:
    source-dirs: regex-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  regex-delim-unordered:
    source-dirs: regex-delim-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  regex-nomemo-unordered:
    source-dirs: regex-nomemo-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  regex-delim-nomemo-unordered:
    source-dirs: regex-delim-nomemo-unordered
    main: Main.hs
    dependencies:
      - grisette-unordered
  cosette-unordered:
    source-dirs: cosette-unordered
    main: Benchmark/Main.hs
    dependencies:
      - grisette-unordered
  cosette-optimized-merge-unordered:
    source-dirs: cosette-optimized-merge-unordered
    main: Benchmark/Main.hs
    dependencies:
      - grisette-unordered
